# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ada05f263fc59f9507fbecc4a6b820c99e4ea8b623155fe38b1c012eab43ce7f09ca320bc8ccc683d3b2335b69ceb8bc342b1f19bdaf4340dd384300eb01fc5

test:
  secret_key_base: 5c49e7e0feb38f8e2cfeba29fe01d21be6a64e5f0090f0f37eb1cb80e9dbfff4c2a966ad5943f58e16c093e60f63df1eb14f389854aa9c25861bcb708bbfe9d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
